networks:
  default:

services:
  ssh-honeypot:
    image: 'ghcr.io/droberson/ssh-honeypot:latest'
    build: .
    ports:
      - '22:2022'
    volumes:
      - log:/home/honeycomb/log
      - rsa:/home/honeycomb/rsa     
    networks:
      - default
    restart: unless-stopped

volumes:
  log:
    driver: local
  rsa:
    driver: local
